// <auto-generated />
using System;
using GroomingSalonApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroomingSalonApp.Migrations
{
    [DbContext(typeof(SalonModel))]
    [Migration("20181202204048_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroomingSalonApp.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AppointmentDate");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CustomerId");

                    b.Property<int>("PetId");

                    b.Property<int?>("ServiceId");

                    b.HasKey("AppointmentId")
                        .HasName("PK_AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("GroomingSalonApp.CustomerAccount", b =>
                {
                    b.Property<string>("EmailAddress")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CustomerFN")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CustomerId");

                    b.Property<string>("CustomerLN");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("Zip");

                    b.HasKey("EmailAddress")
                        .HasName("PK_CustomerId");

                    b.ToTable("CustomerAccounts");
                });

            modelBuilder.Entity("GroomingSalonApp.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Breed");

                    b.Property<int>("CustomerId");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("PetName");

                    b.Property<string>("Species");

                    b.HasKey("PetId")
                        .HasName("PK_PetId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("GroomingSalonApp.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceType");

                    b.HasKey("ServiceId")
                        .HasName("PK_ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GroomingSalonApp.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatePaid");

                    b.Property<int>("EmailAddress");

                    b.Property<int>("PetId");

                    b.Property<int>("ServiceId");

                    b.Property<double>("ServicePrice");

                    b.HasKey("TransactionId")
                        .HasName("PK_Transactions");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GroomingSalonApp.Appointment", b =>
                {
                    b.HasOne("GroomingSalonApp.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");
                });
#pragma warning restore 612, 618
        }
    }
}
